const products = [
  { id: "1", name: "juice", price: 2.5 },
  { id: "2", name: "candy bar", price: 3 },
  { id: "3", name: "donut", price: 1.4 },
  { id: "4", name: "skittles", price: 3.1 },
  { id: "5", name: "soda", price: 2.8 },
  { id: "6", name: "chips", price: 2 },
  { id: "7", name: "cookies", price: 2.6 },
  { id: "8", name: "ice cream", price: 4 },
  { id: "9", name: "water", price: 1 },
  { id: "10", name: "gum", price: 0.5 },
  { id: "11", name: "brownie", price: 3.2 },
  { id: "12", name: "energy drink", price: 3.5 },
  { id: "13", name: "granola bar", price: 2.3 },
  { id: "14", name: "popcorn", price: 1.9 },
  { id: "15", name: "fruit snacks", price: 2.1 },
  { id: "16", name: "pretzels", price: 1.8 },
  { id: "17", name: "lemonade", price: 2.7 },
  { id: "18", name: "milkshake", price: 4.5 },
  { id: "19", name: "trail mix", price: 3.3 },
  { id: "20", name: "beef jerky", price: 5 },
  { id: "21", name: "iced tea", price: 2.4 },
  { id: "22", name: "muffin", price: 2.2 },
  { id: "23", name: "cupcake", price: 2.6 },
  { id: "24", name: "hot chocolate", price: 3.4 },
  { id: "25", name: "banana chips", price: 2 },
  { id: "26", name: "protein bar", price: 3.6 },
  { id: "27", name: "pudding", price: 1.5 },
  { id: "28", name: "sparkling water", price: 2.9 },
  { id: "29", name: "yogurt", price: 2.3 },
  { id: "30", name: "smoothie", price: 4.2 },
];

module.exports = products;
